org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

# Maven Central coordinates / POM (shared across library modules)
GROUP=com.xmoney
VERSION_NAME=1.0.0

POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/xMoney-Payments/xmoney-android
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo
POM_SCM_URL=https://github.com/xMoney-Payments/xmoney-android
POM_SCM_CONNECTION=scm:git:git://github.com/xMoney-Payments/xmoney-android.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/xMoney-Payments/xmoney-android.git
POM_DEVELOPER_ID=xmoney
POM_DEVELOPER_NAME=xMoney
POM_DEVELOPER_URL=https://github.com/xMoney-Payments
